services:
  app:
    build: .
    container_name: wpopapi-app
    volumes:
      - ./app/data:/app/data
    environment:
      - DATABASE_URL=sqlite+aiosqlite:////app/data/app.db
      - TILE_CACHE_DIR=/app/data/tiles
    ports:
      - "8002:8002"
    restart: always

